### ISSUE TITLE
[restore from a private key] can't dismiss keyboard and an invalid address warning message

### ISSUE THREAD

**Issue by dakeshi** [gettyio/tronwallet-mobile#420]
## issue description
As following instruction on [tweet message](https://twitter.com/TronWalletMe/status/1038050525164527616), I was trying to import my wallet using a private key.  But I can not find out how to dismiss keyboard after I've filled up my address and private key. 

and there are one more bug related to wallet address warning message with scan address button.

## expected results
- dismiss the keyboard
When I tap any screen excepting textfield area, keyboard should be dismissed.
- address warning 
When I scan valid address using scan address button, it should be disappeared "invalid warning message"
(in the case of paste my address using clipboard button, it is working well I expected)

## bug reproduction
- dismiss keyboard
1. paste or scan wallet address
2. keyboard will be appeared
3. paste private key
4. tap anywhere to dismiss keyboard(it does not working though)
5. can not click "import" button without dismissing keyboard(=impossible to import from private key)

- address warning 
1. input valid address (pasting it from clipboard or using scan button)
2. delete some address text to make warning message
3. input valid address using scan address button
4. you can see remained invalid address warning message even if it is valid.
 
## testing env
- iOS 11.4.1, iphone5S
- tronwallet version: 1.1.6

**Comment by pedrobertao** [comment]
Fixed on #422
