### ISSUE TITLE
Freezing additional TRX automatically extends the expiry date of previously frozen TRX

### ISSUE THREAD

**Issue by OneCoinWillRuleThemAllTRX** [gettyio/tronwallet-mobile#429]
If I freeze 100 TRX on 1st Jan the expiry date would be Jan 4th for the 100 TRX

On 2nd Jan  I decide to freeze an additional 50 TRX which would mean the expiry date is 5th Jan for the 50 TRX.

It seems that if I freeze the additional TRX it automatically extends the expiry date of my 100 TRX?

**Comment by dbuarque** [comment]
It will freeze everything again.
