### ISSUE TITLE
untranslated strings has appeared. 

### ISSUE THREAD

**Issue by dakeshi** [gettyio/tronwallet-mobile#442]
## issue description
it seems that some strings has not translated because these strings are missing on crowdin.

## bug reproduction
1. change langs to korean
2. tap address book

## screenshots
![untranslated_tron_wallet](https://user-images.githubusercontent.com/8563047/45726773-a5581a00-bbfb-11e8-90e1-f43ebeea107f.jpg)

## testing env
- iOS 11.4.1, iphone5S
- tronwallet version: 1.2

**Comment by pedrobertao** [comment]
Thanks for the report. We will be fixing this ASAP

**Comment by pedrobertao** [comment]
Fixed on #459
