### ISSUE TITLE
source string needs to replace with "public address"

### ISSUE THREAD

**Issue by dakeshi** [gettyio/tronwallet-mobile#456]
## issue description
I think that it needs to use "public address" rather than "public key" in these messages. 

- Public Key copied to the clipboard
- To scan the public key the app needs your permission to access the camera.

please update them on crowdin too after applied on the app.

## testing env
- iOS 11.4.1, iphone5S
- tronwallet version: 1.2

**Comment by pedrobertao** [comment]
Thanks for the report. We will fix this ASAP
