### ISSUE TITLE
Export private key

### ISSUE THREAD

**Issue by JamesHutchison** [gettyio/tronwallet-mobile#468]
In the event the wallet quits functioning (bug/etc) I'd like to be able to export private key back-ups so I can import them into an alternative wallet.

Common use cases:
- TronScan API or some other wallet dependency becomes unavailable
- Software update on phone or update on wallet breaks functionality (for example, imagine doing an update and the wallet now crashes at start-up)
- Send wallet as gift to friends and family

**Comment by pedrobertao** [comment]
If you have your seed words, there are plenty of wallets that you can use with it. We are working hard to prevent that kind of scenario to not happen again. For now we will not provide this feature.
