### ISSUE TITLE
IOS wallet crashes after update 

### ISSUE THREAD

**Issue by sqrrl22** [gettyio/tronwallet-mobile#471]
I've updated my perfectly fine working iOS wallet a couple of days ago and it won't start anymore since. The startup screen shows for half a second but nothing afterwards, it falls back to the home screen. System is 9.3.5 (yes, I know, it's old... but your description says, the app would run on it)

**Comment by pedrobertao** [comment]
Can you provide me the version of the APP ?

**Comment by sqrrl22** [comment]
Sure, it's 1.2.7

**Comment by pedrobertao** [comment]
Please, try to update your APP to 1.2.8. It is available in the App Store. If the error persists please try to reinstall the APP. 
Or else, post it here.

**Comment by sqrrl22** [comment]
Thanks - could you put v1.2.8 on the (European) app store? I still see 1.2.7 ...
