### ISSUE TITLE
Switch push notification doesn't save

### ISSUE THREAD

**Issue by MathijsBok** [gettyio/tronwallet-mobile#472]
When I switch the button to yellow of the option Push Notifications it stays yellow all the time. But when I close the app completely and re-open the app then the switch is grey (off).

**Comment by pedrobertao** [comment]
Thanks for the report. We will fix asap

**Comment by MathijsBok** [comment]
I have test version 1.2.19 and the switch is still switching off when you close the app completely. But notifications from app to app are coming as push notification, still when the switch is off.
