### ISSUE TITLE
Dutch translation rest wallet

### ISSUE THREAD

**Issue by MathijsBok** [gettyio/tronwallet-mobile#473]
![photo_2018-09-30_19-44-42](https://user-images.githubusercontent.com/42490224/46260734-12b45680-c4ea-11e8-88cc-5efb2043886b.jpg)

Wrong translation in Dutch. Where can we edit the string on Crowdin ??

**Comment by pedrobertao** [comment]
https://crowdin.com/project/tronwallet
Please, try to access this item and make the necessary corrections.

**Comment by MathijsBok** [comment]
Fixed, https://crowdin.com/translate/tronwallet/6/en-nl#1439

**Comment by pedrobertao** [comment]
Thanks @MathijsBok We are going to review. Please use the crowdin website mentioned above. We have an automatized system to include these translations.
