### ISSUE TITLE
React-Native Link crash

### ISSUE THREAD

**Issue by leonardomarciano** [gettyio/tronwallet-mobile#474]
Estou enfrentando um crash no react-native link no stock-repository.

MacOS Sierra;
Node 8.11;
RN: 0.57;

**Comment by pedrobertao** [comment]
Please. Write your questions in English as this is a global project. But, what package is the react native link giving the error ? 
Can you print the log ?

**Comment by leonardomarciano** [comment]
In both MacOS and Windows, a detailed error does not appear:

![image](https://user-images.githubusercontent.com/39866296/46381088-2c38d800-c67b-11e8-812a-8e215f8483f7.png)

**Comment by leonardomarciano** [comment]
I found the module that is returning error: react-native-biometrics
