### ISSUE TITLE
When trying to copy to clipboard, the message is cut in half

### ISSUE THREAD

**Issue by KeinP** [gettyio/tronwallet-mobile#478]
Korean/English version, the Lower side of the box is cut off
![image](https://user-images.githubusercontent.com/43856919/46487131-3ead4000-c83a-11e8-9839-be5c62c49292.png)
![image](https://user-images.githubusercontent.com/43856919/46487141-42d95d80-c83a-11e8-9b50-0601aa9b0d56.png)

**Comment by pedrobertao** [comment]
This was fixed on the latest version. Please update your app and reopen this issue if this bug persists.
