### ISSUE TITLE
Funds 

### ISSUE THREAD

**Issue by Tadlo1** [gettyio/tronwallet-mobile#491]
I have made a transfer from my tron scan wallet 2 days ago and it has not appeared on my Tron wallet. I knot it was the correct address as it is shown with another transaction on Tron scan wallet transfers to the same Tron wallet address... Demo didn't go well to a potential adopter..

**Comment by MathijsBok** [comment]
Hello,
Can you submit a request on Intercom, through www.tronwallet.me
There you can make an support ticket. I will help you there.

Kind Regards, 
Mathijs

**Comment by Tadlo1** [comment]
Sorry. My bad 🤗 made a mistake and sent it too another person I was demonstrating too, who did open an account. 

Kind Regards 
Mark J Wallace
