### ISSUE TITLE
Wallet refreshing

### ISSUE THREAD

**Issue by MathijsBok** [gettyio/tronwallet-mobile#496]
Is it possible to add a feauture that when you click on the mainscreen wallet button that the amount of token automatic refreshes. So when I switch screens and press the mainscreen wallet button that the token amount info refresh automatic. So when I did a transaction that the amount automatic refresh when I hit the Wallet Button.

I test version 1.2.19

**Comment by pedrobertao** [comment]
Hey @MathijsBok. We have had some performance issue with this and temporarily remove it. Now I will try to come back with it this function. If everything runs well it will be released next version.
