### ISSUE TITLE
Test results version 1.2.19

### ISSUE THREAD

**Issue by MathijsBok** [gettyio/tronwallet-mobile#500]
I have tested version 1.2.19 and have not seen any urgent issues. Everything works with voting, freeze, send and recieve.

- Maybe you can make the Biometry access automatic, so that you don't have to hit a button before you can use the biometry access ?

- And in the transaction list now you see the name of your addressbook contact, but it's the @ name, instead the regular name. Maybe switch field name ?

- When I setup my account as EUR coin then in the statistics section with the graph, the coin symbol stays a dollar sign, but the numbers are changing for EUR count ?

I really like the popup that comes when you hit a contact in your addressbook. Very nice visual.

**Comment by pedrobertao** [comment]
Thanks @MathijsBok . We are reviewing the Biometry access and we will work for the next release. 
The contact in the addressbook was the determined by the designer.
About the EUR coin is just a default sign. We haven't thought about custom currency signs yet. Thanks for the touch. 

We are at the version v1.2.23 now. Please keep updating your app :D

**Comment by MathijsBok** [comment]
I will do @pedrobertao. I have version 1.2.25 now
