### ISSUE TITLE
Test results version 1.2.25 IOS

### ISSUE THREAD

**Issue by MathijsBok** [gettyio/tronwallet-mobile#503]
App crashes at the following moment :
1. Open the app
2. Do what you need to do
3. Lock your phone
4. Unlock your phone 
5. App crashes and close.
** This also happens when app is running on background. When you set back the app in background and re-open it, the app crashes.

Notification button still not save the prefered selection (on/off). Stays always off. But notifications works always.

Token price TWX is still on 0.1 TRX instead 0.3 TRX

**Comment by pedrobertao** [comment]
@MathijsBok Thanks for the feedback. I already identified the background crash. We will be releasing a fix today. We will try to fix this notification problem as well.

**Comment by MathijsBok** [comment]
Also transaction list is not updating. Transactions are confirmed but in app not.

**Comment by pedrobertao** [comment]
@MathijsBok There is a 1.2.26 to be released today.

**Comment by MathijsBok** [comment]
What is changed or fixed ?

**Comment by pedrobertao** [comment]
@MathijsBok 1.2.26 is out. Fixing the crash and other minor fixes
