### ISSUE TITLE
Test result version 1.2.26

### ISSUE THREAD

**Issue by MathijsBok** [gettyio/tronwallet-mobile#506]
Send transactions are confirmed on Tronscan, but in app stays unconfirmed and a red line. 

![9c80bfb2-55ba-4a9f-9679-c4ab01794660](https://user-images.githubusercontent.com/42490224/46978100-3ec8fd80-d0ce-11e8-8c54-9f16c73014f1.png)
![0a2548fd-3b29-4bb4-b6c7-a3e100f6e3ef](https://user-images.githubusercontent.com/42490224/46978101-3ec8fd80-d0ce-11e8-9643-3419726e79d2.png)

**Comment by pedrobertao** [comment]
@MathijsBok there seems to be an issue with the tronscan api not the app itself. We are aware of that

**Comment by MathijsBok** [comment]
The notification button works. It stays on when app is closed and re-opened.

**Comment by MathijsBok** [comment]
I have tested the notification button. When the button stands on OFF, then I don't get a push notification, but also the transaction doesn't come in the transaction list off the reciever address where the button stands on OFF.

When the button stands on ON then the push notification comes, and the transaction is also displayed in the transaction list of the recieve address where the button stands on ON.
