### ISSUE TITLE
Test Result 1.2.27

### ISSUE THREAD

**Issue by MathijsBok** [gettyio/tronwallet-mobile#508]
I have tested the notification button. When the button stands on OFF, then I don't get a push notification, but also the transaction doesn't come in the transaction list off the reciever address where the button stands on OFF.

When the button stands on ON then the push notification comes, and the transaction is also displayed in the transaction list of the recieve address where the button stands on ON.

**Comment by MathijsBok** [comment]
Yes you are right.

**Comment by MathijsBok** [comment]
Strange, When I send a transaction to version 1.2.27 the transaction list on 1.2.27 isn't updating when the switch is OFF.  Maybe a Tronscan issue, API ?

**Comment by pedrobertao** [comment]
Hmm The tronscan issue is about not confirming the Transactions. Let me check if this is an error from your app only
