### ISSUE TITLE
Crashing every time

### ISSUE THREAD

**Issue by danilotg** [gettyio/tronwallet-mobile#514]
Crashing every time I click on my transactions view.

![fa5878a2-a057-4b48-af8f-b1214fe83a80](https://user-images.githubusercontent.com/16511438/47125486-832cd880-d249-11e8-84b6-843bd9e7b320.jpeg)

**Comment by pedrobertao** [comment]
@danilotg which version ?

**Comment by danilotg** [comment]
V1.2.33

Regards,
Danilo Goncalves

On Oct 22, 2018, at 7:30 AM, pedrobertao <notifications@github.com<mailto:notifications@github.com>> wrote:


@danilotg<https://github.com/danilotg> which version ?

**Comment by danilotg** [comment]
Fixed
