### ISSUE TITLE
Test result 1.2.30

### ISSUE THREAD

**Issue by MathijsBok** [gettyio/tronwallet-mobile#515]
Currently tested version 1.2.30

The transaction list is not syncing. Only send transactions are saved in the transaction list. When I recieve a transaction it isn't displayed in mijn list.

For the rest I don't see any issues. Maybe there are some, but I didn't find it.

**Comment by pedrobertao** [comment]
@MathijsBok Thanks again. We are delaying our released because we are working on a solution to fix the transactions list. That is an TronScan Api fault. Thanks for the feedbacks. I'm writing a testing script routine now. What do you think ?


>First Tests
```1. Create Account, check all pages
2. Restore Account, check all pages
3. Import Account, check all pages```

With Restored Account
```1. Vote Transaction
2. Transfer TRX
3. Transfer Token
4. Freeze (Try to Unfreeze if possible)
5. Participate (TWX)
6. After Each Transactiosn check if Transaciton List Data is correct
7. Create Account
8. Delete and Restore Accounts
9. Generate Request
10. Make a payment using scan```
Wallet  Tests
```1. Restore Wallet inside App
2. Reset Wallet 
3. Backup Wallet``` 
General Tests
```1. Test Search Votes and Participate (Look for TronWallet and TWX)
2. Add an contact
3. Use all options for a single Contact: Transactions, Edit, Send, Delete
4. Access token information from Balance```
Settings Tests
```1. Change Language
2. Change currency
3. Use Token Filter
4. Check About and Help Center
5. Toggle Verified Tokens Only
6. Toggle Biometry (If available)
7. Toggle Always ask PIN
8. Toggle Notifications```

>

**Comment by pedrobertao** [comment]
No. On iOs there is around 3 testers and android around 4.

**Comment by pedrobertao** [comment]
On iOS there is 3-4 testers and on android also. This is just a routine. Nothing is automatic yet, just to guide you on the main features.
