### ISSUE TITLE
Different length of seed on backup/restore activities

### ISSUE THREAD

**Issue by ghostwg** [gettyio/tronwallet-mobile#528]
1. Open 'Backup wallet' - seed length 24 words.
2. Open 'Restore wallet' - in Window you can see message about input 12 words seed.

Unfoturnately on the road, so cant test does it pass 24 words seed, maybe mistake in sentences.

**Comment by pedrobertao** [comment]
Are you seeing a 24 words length seed ?

**Comment by ghostwg** [comment]
When backup 24, when restore i see, please type your  12 seed words here

**Comment by dbuarque** [comment]
![2018-10-26 14 16 13](https://user-images.githubusercontent.com/559571/47592817-bc400980-d929-11e8-909e-85490be52f5a.jpg)

**Comment by pedrobertao** [comment]
Where did you get 24 words ? Outside the App ?
