### ISSUE TITLE
would you check terms and conditions?

### ISSUE THREAD

**Issue by dakeshi** [gettyio/tronwallet-mobile#532]
In https://github.com/gettyio/tronwallet-mobile/blob/development/src/utils/translations/en.json

> These terms and conditions are governed by and construed in accordance with the laws of Vancouver, Canada and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.

Vancouver? getty.io has an office on Vancouver too?

**Comment by pedrobertao** [comment]
I can't tell you much about it but we will have TronWalletMe office placed on Vancouver.

**Comment by dakeshi** [comment]
> will have TronWalletMe office placed on Vancouver.

 If it is true, I'd like to check this date too. 

In the conditions and terms, "This policy is effective as of 1 July 2018." 

I guess that it is possible to register the company with paper work before setting up an office but it needs to double check to make it correct.

**Comment by dakeshi** [comment]
this is another issue. In terms.

> By accessing the website at http://tronwallet.me, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.

It seems that it is related to tronwallet.me website rather than tronwallet mobile app itself.

**Comment by pedrobertao** [comment]
Fixed already
