### ISSUE TITLE
suggestion for searchPreview title on voting screen

### ISSUE THREAD

**Issue by dakeshi** [gettyio/tronwallet-mobile#533]
The search preview feature shows us SRC list who receive my votes. So, the current title "Suggestions - Most Voted" is not matched with its intention.

# suggestion
- The current my voting status
- my voting lists

**Comment by pedrobertao** [comment]
"Suggestions - My latest votes" @dakeshi  ?

**Comment by dakeshi** [comment]
i think that it doesn't need to add "suggestion" in this context. "My latest votes" looks good though.

**Comment by pedrobertao** [comment]
#534
