### ISSUE TITLE
typo in terms and conditions

### ISSUE THREAD

**Issue by dakeshi** [gettyio/tronwallet-mobile#536]
https://github.com/gettyio/tronwallet-mobile/blob/development/src/utils/translations/en.json

>Further, TronWallet does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.n

this site.n should be "this site."

**Comment by pedrobertao** [comment]
#538
