### ISSUE TITLE
Test Version 1.2.52

### ISSUE THREAD

**Issue by MathijsBok** [gettyio/tronwallet-mobile#556]
Transaction updates freezed when app is opened from background.
Then the account card isn't updating numbers, and transactionlist is freezed, the button to refresh doesn't work and doesn't rotate to refresh

Also after making 2-3 transactions

**Comment by MathijsBok** [comment]
The page ADDRESSBOOK is to high aligned. On Iphone XS the name ADDRESSBOOK is half after the camera position

**Comment by pedrobertao** [comment]
Noted both issues. We we be fixing soon. Thanks @MathijsBok
