### ISSUE TITLE
App crashes when open Transactions screen

### ISSUE THREAD

**Issue by Vogeles** [gettyio/tronwallet-mobile#570]
Every time I switch to Transactions screen, app crash. it shows white screen first and then crash completely. 

I am using 4 accounts in the app:

Account 1: crash completely immediately
Account 2: works
Account 3: displays white screen over whole display and freeze when try to scroll
Account 4: displays white screen over whole display and freeze immediately after screen opening

Seems that some types of transactions break this screen and app.

TBcxE1BJtQ1ex1jFETAWnVZoRHvFGzj4U3 this account crash completely.

Seems like accounts where I traded on DEX exchange are failing.

**Comment by scc9870** [comment]
I think that problem that app is failing are smart contract operations which are not supported by TronWallet. Just guess but account withouot this operation type is not failing.

**Comment by Vogeles** [comment]
So I know what is causing the problem fith app crash. It fails everytime because of filter of tokens. I had plenty of tokens filtered out and when I removed all filters then app is working.

**Comment by Vogeles** [comment]
issue fixed with new release
