### ISSUE TITLE
[Suggestion] Address field should have icon for contact selection

### ISSUE THREAD

**Issue by Vogeles** [gettyio/tronwallet-mobile#576]
When try to send tokens to some address, then I can choose only from QR or from clipboard, there should be 3rd icon to select saved contact. 

Today I have to go to contacts first and then select transfer operation which is not user friendly flow. I should select operation first and then choose address if it is in my address book already.

**Comment by dbuarque** [comment]
Hi mate, this feature was already planned and is under development. Thanks for your contribution.
