### ISSUE TITLE
Response error code: 500

### ISSUE THREAD

**Issue by JingyuQian** [gettyio/tronwallet-mobile#621]
Hi,
I was trying to run the app on an emulator when I encountered this error: 
app version: 1.2.39 (this problem also exists in 1.3.41)
![image](https://user-images.githubusercontent.com/13508878/50038170-f5af0000-ffcf-11e8-9345-944ac96b6dac.png)
The command I used was `react-native run-android`

Seems like there is a file missing but I don't know how to resolve this.
Thanks!

**Comment by JingyuQian** [comment]
Is this a file that needs to be generated by the user?

**Comment by dbuarque** [comment]
Hey mate, you need an api key to be able to run the project. It will be available next year.
